spring:
  application:
    name: config-server
  profiles:
    active: native

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server:localhost}:5050/eureka
