spring:
  application:
    name: config-server
  profiles:
    active: native

server:
  port: 9999

management:
  server:
    port: 9998
  endpoints:
    web:
      exposure:
        include: health,env
