eureka:
  instance:
    hostname: discovery-server-2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server-1:${server.port}/eureka/,http://discovery-server-3:${server.port}/eureka/
