server:
  port: 8080

my:
  val: discovery

logging:
  level:
    reactor.netty.http.client.HttpClient: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway.filter.GatewayMetricsFilter: INFO

httpbin:
  uri:  https://httpbin.org

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
      routes:
        - id: httpbin
          uri: ${httpbin.uri}
          predicates:
            - Path=/httpbin/**
            - Method=GET,POST,DELETE
          filters:
            - StripPrefix=1
            - AddRequestHeader=header-1, values-1
            - AddRequestHeader=header-2, values-2
            - AddRequestHeader=header-3, values-3
        - id: aaa
          uri: lb://svc-aaa
          predicates:
            - Path=/aaa/**
            - Method=GET
          filters:
            - StripPrefix=1
            - AddRequestHeader=my-header, values-aaa
        - id: bbb
          uri: lb://svc-bbb
          predicates:
            - Path=/bbb/**
            - Method=GET
          filters:
            - StripPrefix=1
            - AddRequestHeader=my-header, values-bbb
